version: '3'
services:
  frontend:
    build:
      context: ./Website/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./Website/backend
      dockerfile: Dockerfile
